function getTidyPanelTabId(panel)
{
    if (!(panel instanceof HTMLElement)) return "";

    return panel.dataset.tab
        || panel.dataset.tabId
        || panel.dataset.tabContentsFor
        || "";
}

function resolveTidyPanelTargetRoot(panel)
{
    if (!(panel instanceof HTMLElement)) return null;

    const tabId = getTidyPanelTabId(panel);
    if (tabId === "attributes") return panel;

    const itemRoot = panel.querySelector(
        '[data-tidy-sheet-part="items-container"], [data-tidy-sheet-part="inventory"], [data-tidy-sheet-part="spellbook"], [data-tidy-sheet-part="item-table"], .tidy-table-container, .tidy-table-row-container, .tidy-table-row, [data-tidy-sheet-part="item-table-row"], .item[data-item-id], [data-item-id][tabindex], [data-uuid][tabindex]'
    );
    if (itemRoot instanceof HTMLElement) return itemRoot;

    return null;
}

export function buildSheetAdapters()
{
    return [
        {
            id: "tidy5e-classic",
            matches: (app, root) => root?.dataset?.sheetModule === "tidy5e-sheet" && root.classList.contains("classic"),
            useWholePanelForTargets: false,
            localTabReturnHotkey: true,
            preferRootClassTabIdForHotkey: false,
            skipInventoryRowsAsTargets: true,
            resolveTargetRoot: resolveTidyPanelTargetRoot,
            contentRootSelectors: [
                '[data-tidy-sheet-part="abilities"]',
                '[data-tidy-sheet-part="ability-scores"]',
                '[data-tidy-sheet-part="saving-throws"]',
                '[data-tidy-sheet-part="inventory"]',
                '[data-tidy-sheet-part="spellbook"]',
                '[data-tidy-sheet-part="item-table"]',
                '.tidy-table-row-container[data-item-id]',
                '.tidy-table-row[data-item-id]',
                '[data-tidy-sheet-part="item-table-row"][data-item-id]',
                '[data-tidy-sheet-part="skills-list"]',
                '[data-tidy-sheet-part="tools-list"]',
                '.tidy-table-container',
                '[data-tidy-sheet-part="items-container"]',
                '.skills-list-container',
                '.skills.card',
                '.abilities.card',
                '.saves.card',
            ],
            entrySelectors: [
                '[data-tidy-sheet-part="skill-roller"]',
                '.use-ability-roll-button',
                '[data-tidy-sheet-part="ability-save-roller"]',
                '.ability-save-roller',
                '.tidy-table-row-use-button',
                '.item-image',
                '.item-name',
                '.quantity-tracker-input',
                '.command.decrementer',
                '.command.incrementer',
                '.item-toggle',
                '.tidy-table-button',
                '.tidy5e-skill-name',
                '.tool-roller',
                '.tool-check-roller',
                '.ability-mod',
                '.ability-save',
                '.trait-item',
                '.item-name[role="button"]',
            ],
            panelTargetSelectors: [
                '[data-tidy-sheet-part="skill-roller"]',
                '.use-ability-roll-button',
                '[data-tidy-sheet-part="ability-save-roller"]',
                '.ability-save-roller',
                '.tidy-table-row-use-button',
                '.item-image',
                '.item-name',
                '.quantity-tracker-input',
                '.command.decrementer',
                '.command.incrementer',
                '.item-toggle',
                '.tidy-table-button',
                '.tidy5e-skill-name',
                '.tool-roller',
                '.tool-check-roller',
                '.ability-mod',
                '.ability-save',
                '.trait-item',
                '.item-name[role="button"]',
                '.button',
                '.inline-transparent-button',
            ],
            excludedPanelTargetSelectors: [
                '.skill-expand-button',
                '.skill-ability',
                '.button-icon-only.proficiency',
                '.action-bar button',
                '.sort-menu-option',
                '.clear-all-filters',
                '.currency-conversion',
                '.item-create',
                '.expand-button.button-toggle',
            ],
        },
        {
            id: "tidy5e-default",
            matches: (app, root) => root?.dataset?.sheetModule === "tidy5e-sheet",
            useWholePanelForTargets: false,
            localTabReturnHotkey: true,
            preferRootClassTabIdForHotkey: false,
            skipInventoryRowsAsTargets: true,
            resolveTargetRoot: resolveTidyPanelTargetRoot,
            contentRootSelectors: [
                '[data-tidy-sheet-part="abilities"]',
                '[data-tidy-sheet-part="ability-scores"]',
                '[data-tidy-sheet-part="saving-throws"]',
                '[data-tidy-sheet-part="inventory"]',
                '[data-tidy-sheet-part="spellbook"]',
                '[data-tidy-sheet-part="item-table"]',
                '.tidy-table-row-container[data-item-id]',
                '.tidy-table-row[data-item-id]',
                '[data-tidy-sheet-part="item-table-row"][data-item-id]',
                '[data-tidy-sheet-part="skills-list"]',
                '[data-tidy-sheet-part="tools-list"]',
                '.tidy-table-container',
                '[data-tidy-sheet-part="items-container"]',
                '.skills-list-container',
                '.skills.card',
                '.abilities.card',
                '.saves.card',
            ],
            entrySelectors: [
                '[data-tidy-sheet-part="skill-roller"]',
                '.use-ability-roll-button',
                '[data-tidy-sheet-part="ability-save-roller"]',
                '.ability-save-roller',
                '.tidy-table-row-use-button',
                '.item-image',
                '.item-name',
                '.quantity-tracker-input',
                '.command.decrementer',
                '.command.incrementer',
                '.item-toggle',
                '.tidy-table-button',
                '.tidy5e-skill-name',
                '.tool-roller',
                '.tool-check-roller',
                '.ability-mod',
                '.ability-save',
                '.trait-item',
                '.item-name[role="button"]',
            ],
            panelTargetSelectors: [
                '[data-tidy-sheet-part="skill-roller"]',
                '.use-ability-roll-button',
                '[data-tidy-sheet-part="ability-save-roller"]',
                '.ability-save-roller',
                '.tidy-table-row-use-button',
                '.item-image',
                '.item-name',
                '.quantity-tracker-input',
                '.command.decrementer',
                '.command.incrementer',
                '.item-toggle',
                '.tidy-table-button',
                '.tidy5e-skill-name',
                '.tool-roller',
                '.tool-check-roller',
                '.ability-mod',
                '.ability-save',
                '.trait-item',
                '.item-name[role="button"]',
                '.button',
                '.inline-transparent-button',
            ],
            excludedPanelTargetSelectors: [
                '.skill-expand-button',
                '.skill-ability',
                '.button-icon-only.proficiency',
                '.action-bar button',
                '.sort-menu-option',
                '.clear-all-filters',
                '.currency-conversion',
                '.item-create',
                '.expand-button.button-toggle',
            ],
        },
        {
            id: "dnd5e-default",
            matches: (app, root) => app?.document?.documentName === "Actor",
            useWholePanelForTargets: true,
            localTabReturnHotkey: true,
            preferRootClassTabIdForHotkey: true,
            skipInventoryRowsAsTargets: true,
            entrySelectors: [
                'li.item[data-item-id] .item-name.item-action.rollable',
                'li.item[data-item-id] .activity-name.item-name.item-action.rollable',
                'li.item[data-item-id] .item-control[data-action="equip"]',
                'li.item[data-item-id] .item-control[data-action="toggleExpand"]',
                'li.item[data-item-id] .item-control[data-context-menu]',
                'li.item[data-item-id] .item-toggle',
                '.skill-name',
                '.saving-throw',
                '.ability-check',
                '.item-name',
                '.item-action',
                '.item-control',
                '.rollable',
                '[data-action="roll"]',
                '[data-action]',
                'button',
                'a',
            ],
            panelTargetSelectors: [
                'li.item[data-item-id] .item-name.item-action.rollable',
                'li.item[data-item-id] .activity-name.item-name.item-action.rollable',
                'li.item[data-item-id] .item-control[data-action="equip"]',
                'li.item[data-item-id] .item-control[data-action="toggleExpand"]',
                'li.item[data-item-id] .item-control[data-context-menu]',
                'li.item[data-item-id] .item-toggle',
                '.skill-name',
                '.saving-throw',
                '.ability-check',
                '.item-name',
                '.item-action',
                '.item-control',
                '.rollable',
                '[data-action="roll"]',
                '[data-action]',
                'button',
                'a',
                'input',
                'select',
                'textarea',
            ],
            excludedPanelTargetSelectors: [
                '.filter-control',
                '.adjustment-button',
                '.items-header',
                '.item-header',
                '.midi-info-icon',
                '[data-action="toggleExpand"]',
                '.midi-activity-buttons button',
                '[data-midi-action]',
                '.item-detail.item-quantity input',
                '.item-detail.item-quantity',
                '.item-detail.item-price',
                '.item-detail.item-weight',
                '.item-detail.item-roll',
                '.item-detail.item-formula',
                '.item-detail.item-uses',
                '.pills-group',
                '.pills-group .pill',
                '.pills-group .label',
                '.pills-group h3',
                '.items-header',
                '.items-section > .item-name',
                '.inventory-element > .item-name',
            ],
        },
        {
            id: "generic-actor-sheet",
            matches: () => true,
            useWholePanelForTargets: true,
            localTabReturnHotkey: false,
            preferRootClassTabIdForHotkey: false,
            entrySelectors: [],
            panelTargetSelectors: [],
            excludedPanelTargetSelectors: [],
        },
    ];
}
